WORKSPACE_ROOT_ENV = "LUNAR_ANALYST_WORKSPACE_ROOT"
REQUIRE_NOTEBOOK_SESSION_ENV = "LUNAR_ANALYST_REQUIRE_SESSION_TOKEN"
MARIMO_PYTHON_ENV = "LUNAR_ANALYST_MARIMO_PYTHON"
DEFAULT_WORKSPACE_REL = "scenarios"
DEFAULT_MAX_WS_EVENTS = 5000
DEFAULT_MAX_ASSISTANT_WS_EVENTS = 5000
DEFAULT_MAX_NOTEBOOK_RUN_INFO = 1024
