apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lunar-analyst-workspace
  namespace: lunar-analyst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
